version: '3.3'

services:

  wordpress:
    container_name: cpam_wordpress
    depends_on:
      - db
    image: max2wms/cpam1410
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: password01
    ports:
      - 80:80
      - 443:443
    networks:
      - wp

  db:
    container_name: cpam_mysql
    image: mysql:5.7
    restart: always
    volumes:
      - cpam_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password01
    networks:
      - wp

  phpmyadmin:
    container_name: cpam_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password01
    networks:
      - wp

networks:
  wp:

volumes:
  cpam_data: